import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
//import vueiframe, { VueIframe } from "vue-iframes";
//import { html2canvas } from "html2canvas";
import "./css/global.css";
//import vueHtml2canvas from "vue-html2canvas";
import "@babel/polyfill";
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { dom } from "@fortawesome/fontawesome-svg-core";
library.add(fas, fab);
dom.watch();
import mitt from "mitt";
const emitter = mitt();

const app = createApp(App).use(router);
app.component("font-awesome-icon", fontAwesomeIcon);
app.config.globalProperties.emitter = emitter;
app.mount("#app");
